version: "3.7"

services:
  site:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: hatamiarash7/audio_visualization
    container_name: audio_visualization
    restart: always
    working_dir: /usr/share/nginx/html/
    volumes:
      - ./:/usr/share/nginx/html/
    ports:
      - 13005:80
